spring:
  application:
    name: hyomee
  profiles:
    active: local
  config:
    import:
      - optional:classpath:/config/custom/custom.yml
  messages:
    basename: message/normal,  essage/exception
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace




