##########################################################
# 사용자 정의
##########################################################
user:
  error:
    fillInStackTrace: false
    printStackTrace: true

scheduler:
  poolSize: 5


