spring:
  application:
    name: hyomee
  profiles:
    active: local
  config:
    import:
      - classpath:/config/custom/custom.yml
      - classpath:/config/custom/el.yml
  messages:
    basename: message/message,  essage/exception
    encoding: UTF-8