# 사무실 8.7.1
es:
  host:  192.168.210.52
  port: 9200
  username: elastic
  password: GlFAJO2I=**kk8hjP02g
  schemeName: https
  ssl: fingerprint        # pwd, fingerprint, ca
  fingerprint: 3b4a60ca061ab6a2c9d6289e768bd5a16de824a8126ca51bf8d8454756e8081b
  cadrt: C:\PRJ\hybird\elk

#doc:
#  demoIndex: demo
#  articleIndex: article
tourlistDir: D:\PRJ\project\initData\