# 개인
es:
  host:  172.31.25.224
  port: 9200
  username: elastic
  password: =5k2f8LXRrA69xLk_LgU
  schemeName: https
  ssl: fingerprint        # pwd, fingerprint, ca
  fingerprint: 1f27354472efc0b8c064883a7b26e23274f8479e99dfcf358625527a59c41b94
  cadrt: D:\PRJ\hybird\elk

#doc:
#  demoIndex: demo
#  articleIndex: article
tourlistDir: D:\PRJ\project\initData\